services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    image: babak/parallel-api:latest
    container_name: parallel_api
    ports:
      - "8000:8000"          # expose FastAPI to host
    environment:
      - TZ=Asia/Tehran
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile.web
    image: babak/parallel-web:latest
    container_name: parallel_web
    ports:
      - "8080:8080"          # expose static site to host
    depends_on:
      api:
        condition: service_healthy
    environment:
      - TZ=Asia/Tehran
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 5s
    restart: unless-stopped
