#use nginx official
FROM nginx:latest


#clearing and removing and preparing folder or folders
RUN rm -rf /usr/share/nginx/html/*


#copy the index.html and asset or assets folder
COPY static /usr/share/nginx/html


#copy of nginx configuration
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 8080


CMD ["nginx", "-g", "daemon off;"]

