# Use nginx official
FROM nginx:latest

# Clean default html and copy our static assets
RUN rm -rf /usr/share/nginx/html/*
COPY static /usr/share/nginx/html

# Use a simple HTTP-only nginx conf that listens on 8080
COPY docker/nginx.web.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]
